import {supabase} from "./supabase";import {getTibiaDataCharacter} from "./tibia";import type {Character,SourceSync} from "./types";
export const TARGET_WORLD="Jadebra";
function mapCharacter(x:any){return {...x,world_name:x.worlds?.name??null,guild_name:x.guilds?.name??null} as Character}
export async function allCharacters(){const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("archived",false).order("name");if(error)throw error;return (data??[]).map(mapCharacter) as Character[];}
export async function characters(){return (await allCharacters()).filter(c=>c.monitored&&c.world_name===TARGET_WORLD);}
export async function character(id:string){const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("id",id).single();if(error)throw error;return mapCharacter(data);}
export async function sources(){const {data,error}=await supabase.from("source_syncs").select("*").order("source");if(error)throw error;return data as SourceSync[];}
export async function events(){const [a,b,c,d]=await Promise.all([supabase.from("online_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(100),supabase.from("death_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(100),supabase.from("level_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(50),supabase.from("pvp_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(100)]);for(const r of [a,b,c,d])if(r.error)throw r.error;return [...(a.data??[]).map((x:any)=>({...x,kind:x.kind})),...(b.data??[]).map((x:any)=>({...x,kind:"DEATH"})),...(c.data??[]).map((x:any)=>({...x,kind:"LEVEL_UP"})),...(d.data??[]).map((x:any)=>({...x,kind:"PVP_KILL"}))].filter((x:any)=>x.characters?.worlds?.name===TARGET_WORLD||x.kind==="MASS_LOGIN").sort((x:any,y:any)=>new Date(y.occurred_at).getTime()-new Date(x.occurred_at).getTime());}
function tibiaInfo(j:any){const root=j?.character||j?.characters||j||{};return root?.character||root?.data||root||{}}
async function ensureWorld(name:string){const {data,error}=await supabase.from("worlds").upsert({name},{onConflict:"name"}).select("id").single();if(error)throw error;return data.id as string}
async function ensureGuild(name:string|null,worldId:string){if(!name)return null;const {data:existing}=await supabase.from("guilds").select("id").eq("name",name).eq("world_id",worldId).maybeSingle();if(existing?.id)return existing.id as string;const {data,error}=await supabase.from("guilds").insert({name,world_id:worldId}).select("id").single();if(error)throw error;return data.id as string}
export async function hydrateCharacterWorld(c:{id:string;name:string}){const r=await getTibiaDataCharacter(c.name);const info=tibiaInfo(r.data);const world=String(info?.world||"").trim();if(!world)throw new Error("Não foi possível identificar o servidor de "+c.name);const worldId=await ensureWorld(world);const guildName=typeof info.guild==="string"?info.guild:String(info.guild?.name||"").trim()||null;const guildId=await ensureGuild(guildName,worldId);const patch:any={world_id:worldId,guild_id:guildId,source:"TIBIADATA",data_state:"ATUALIZADO"};if(Number(info.level))patch.level=Number(info.level);if(info.vocation)patch.vocation=String(info.vocation);if(world!==TARGET_WORLD)patch.monitored=false;const {error}=await supabase.from("characters").update(patch).eq("id",c.id);if(error)throw error;return {world,guild:guildName,level:Number(info.level)||null,vocation:info.vocation??null}}
export async function hydratePendingWorlds(limit=1){const rows=await allCharacters();const pending=rows.filter(c=>!c.world_name).slice(0,limit);for(const c of pending){try{await hydrateCharacterWorld(c)}catch(e){console.warn("Falha ao identificar servidor",c.name,e)}}return pending.length}
export async function addCharacter(name:string){const clean=name.trim();if(!clean)throw new Error("Informe o nome do personagem");let {data:existing}=await supabase.from("characters").select("id,name,tags,worlds(name)").ilike("name",clean).maybeSingle();let id=existing?.id as string|undefined;let tags=[...new Set([...(existing?.tags??[]),"PK_SEED"])];if(!id){const ins=await supabase.from("characters").insert({name:clean,monitored:true,source:"MANUAL",data_state:"PENDENTE",confidence:"LOW",tags:["PK_SEED"]}).select("id,name").single();if(ins.error)throw ins.error;id=ins.data.id}else{await supabase.from("characters").update({tags,monitored:true,archived:false}).eq("id",id)}const info=await hydrateCharacterWorld({id,name:clean});if(info.world!==TARGET_WORLD){await supabase.from("characters").update({monitored:false}).eq("id",id);throw new Error(clean+" está em "+info.world+". O PK Radar agora monitora apenas "+TARGET_WORLD+".")}await supabase.from("characters").update({monitored:true,archived:false,tags}).eq("id",id);const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("id",id).single();if(error)throw error;return mapCharacter(data);}
export async function addDiscoveredCharacter(name:string,depth:number){const clean=name.trim();if(!clean)throw new Error("Nome vazio");let {data:existing}=await supabase.from("characters").select("id,name,tags").ilike("name",clean).maybeSingle();let id=existing?.id as string|undefined;const current=existing?.tags??[];const seed=current.includes("PK_SEED");const tags=seed?current:[...new Set([...current.filter((t:string)=>t!=="AUTO_NOISE"&&!t.startsWith("DISCOVERY_DEPTH:")),"AUTO_DISCOVERED","DISCOVERY_DEPTH:"+Math.max(1,depth)])];if(!id){const ins=await supabase.from("characters").insert({name:clean,monitored:true,source:"TIBIA_STALKER",data_state:"AUTO_DESCOBERTO",confidence:"MEDIUM",tags}).select("id,name").single();if(ins.error)throw ins.error;id=ins.data.id}else{await supabase.from("characters").update({tags,monitored:true,archived:false}).eq("id",id)}const info=await hydrateCharacterWorld({id,name:clean});if(info.world!==TARGET_WORLD){await supabase.from("characters").update({monitored:false}).eq("id",id);throw new Error(clean+" não está em "+TARGET_WORLD)}await supabase.from("characters").update({monitored:true,archived:false,tags}).eq("id",id);const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("id",id).single();if(error)throw error;return mapCharacter(data);}
async function detectMassLogin(at:string){const since=new Date(new Date(at).getTime()-5*60*1000).toISOString();const {data}=await supabase.from("online_events").select("character_id,occurred_at,characters(name,worlds(name))").eq("kind","LOGIN").gte("occurred_at",since).order("occurred_at");const map=new Map<string,string>();for(const x of data??[]){if(x.character_id&&x.characters?.worlds?.name===TARGET_WORLD)map.set(x.character_id,x.characters?.name||x.character_id)}if(map.size<4)return;const names=[...map.values()];const bucket=Math.floor(new Date(at).getTime()/300000);await supabase.from("alerts").upsert({title:"MASS LOG DETECTADO",body:names.length+" personagens de Jadebra entraram em até 5 minutos: "+names.join(", "),triggered_at:at,dedupe_key:"mass-login:"+bucket,metadata:{count:names.length,threshold:4,windowMinutes:5,names}},{onConflict:"dedupe_key"});await supabase.from("online_events").upsert({kind:"MASS_LOGIN",occurred_at:at,source:"TIBIA_STALKER",confidence:"HIGH",dedupe_key:"mass-login-event:"+bucket,metadata:{count:names.length,threshold:4,windowMinutes:5,names}},{onConflict:"dedupe_key"})}
export async function updateOnline(name:string,isOnline:boolean,occurredOn:string,source:"TIBIA_STALKER"|"TIBIADATA"="TIBIA_STALKER"){const {data:char}=await supabase.from("characters").select("id,online,worlds(name)").ilike("name",name).maybeSingle();if(!char||char.worlds?.name!==TARGET_WORLD)return;if(char.online===isOnline)return;const occurred=new Date(occurredOn||Date.now()).toISOString();const kind=isOnline?"LOGIN":"LOGOUT";await supabase.from("characters").update({online:isOnline,last_login_at:isOnline?occurred:undefined,last_event_at:occurred,source,data_state:"ATUALIZADO",confidence:source==="TIBIA_STALKER"?"HIGH":"MEDIUM"}).eq("id",char.id);await supabase.from("online_events").upsert({character_id:char.id,kind,occurred_at:occurred,source,confidence:source==="TIBIA_STALKER"?"HIGH":"MEDIUM",dedupe_key:`${source.toLowerCase()}:${name.toLowerCase()}:${kind}:${occurred}`,metadata:{name,reconciled:source==="TIBIADATA"}},{onConflict:"dedupe_key"});if(kind==="LOGIN")await detectMassLogin(occurred)}
function onlineNamesFromWorld(j:any){const list=j?.world?.online_players??j?.world?.players_online??j?.worlds?.players_online??j?.players_online??[];return new Set((Array.isArray(list)?list:[]).map((x:any)=>String(x?.name??x).toLowerCase()))}
export async function reconcileWorldOnline(emitEvents=false){const r=await fetch(`https://api.tibiadata.com/v4/world/${encodeURIComponent(TARGET_WORLD)}`,{headers:{accept:"application/json"}});if(!r.ok)throw new Error("TibiaData world HTTP "+r.status);const online=onlineNamesFromWorld(await r.json());const list=await characters();const now=new Date().toISOString();let changed=0;for(const ch of list){const next=online.has(ch.name.toLowerCase());if(next===ch.online)continue;changed++;if(emitEvents)await updateOnline(ch.name,next,now,"TIBIADATA");else await supabase.from("characters").update({online:next,source:"TIBIADATA",data_state:"ATUALIZADO",confidence:"MEDIUM"}).eq("id",ch.id)}return {online:online.size,changed}}
