import {supabase} from "./supabase";import {getTibiaDataCharacter} from "./tibia";import {PK_SEED_NAMES} from "./seeds";import type {Character,SourceSync} from "./types";
export const TARGET_WORLD="Jadebra";
function mapCharacter(x:any){return {...x,world_name:x.worlds?.name??null,guild_name:x.guilds?.name??null} as Character}
function normName(v:string){return v.trim().toLocaleLowerCase("en-US")}
function canonicalScore(x:any,input?:string){
  const seed=PK_SEED_NAMES.find(n=>normName(n)===normName(String(x.name||"")));
  let score=0;
  if(seed&&x.name===seed)score+=10000;
  if(input&&x.name===input.trim())score+=1500;
  if((x.tags??[]).includes("PK_SEED"))score+=1000;
  if(x.source==="MANUAL")score+=300;
  if(!x.archived)score+=150;
  if(x.monitored)score+=100;
  if(x.worlds?.name===TARGET_WORLD)score+=50;
  return score;
}
async function findCharacterInsensitive(name:string){
  const clean=name.trim();if(!clean)return null;
  const {data,error}=await supabase.from("characters").select("id,name,tags,source,monitored,archived,online,level,vocation,created_at,updated_at,last_event_at,last_login_at,world_id,guild_id,worlds(name)").ilike("name",clean).order("created_at",{ascending:true}).limit(20);
  if(error)throw error;
  return [...(data??[])].sort((a:any,b:any)=>canonicalScore(b,clean)-canonicalScore(a,clean)||new Date(a.created_at||0).getTime()-new Date(b.created_at||0).getTime())[0]??null;
}
export async function cleanupCharacterDuplicates(){
  const {data,error}=await supabase.from("characters").select("id,name,tags,source,monitored,archived,online,level,vocation,notes,created_at,last_event_at,last_login_at,world_id,guild_id,worlds(name)");
  if(error)throw error;
  const groups=new Map<string,any[]>();
  for(const ch of data??[]){const key=normName(String(ch.name||""));if(!key)continue;const arr=groups.get(key)??[];arr.push(ch);groups.set(key,arr)}
  let archived=0;
  for(const rows of groups.values()){
    if(rows.length<2)continue;
    const canonicalSeed=PK_SEED_NAMES.find(n=>normName(n)===normName(String(rows[0].name||"")));
    rows.sort((a:any,b:any)=>canonicalScore(b,canonicalSeed)-canonicalScore(a,canonicalSeed)||new Date(a.created_at||0).getTime()-new Date(b.created_at||0).getTime());
    const primary=rows[0],dupes=rows.slice(1);
    const tags=[...new Set(rows.flatMap((x:any)=>x.tags??[]).filter((t:string)=>!t.startsWith("DUPLICATE_OF:")))];
    if(canonicalSeed&&!tags.includes("PK_SEED")&&rows.some((x:any)=>(x.tags??[]).includes("PK_SEED")))tags.push("PK_SEED");
    const latest=(field:string)=>rows.map((x:any)=>x[field]).filter(Boolean).sort((a:string,b:string)=>new Date(b).getTime()-new Date(a).getTime())[0]??null;
    const levels=rows.map((x:any)=>Number(x.level||0)).filter((n:number)=>n>0);
    const patch:any={
      tags,
      monitored:rows.some((x:any)=>x.monitored&&!x.archived),
      archived:false,
      online:rows.some((x:any)=>x.online),
      level:levels.length?Math.max(...levels):primary.level,
      vocation:primary.vocation??rows.find((x:any)=>x.vocation)?.vocation??null,
      world_id:primary.world_id??rows.find((x:any)=>x.world_id)?.world_id??null,
      guild_id:primary.guild_id??rows.find((x:any)=>x.guild_id)?.guild_id??null,
      last_event_at:latest("last_event_at"),
      last_login_at:latest("last_login_at")
    };
    if(canonicalSeed)patch.name=canonicalSeed;
    const up=await supabase.from("characters").update(patch).eq("id",primary.id);if(up.error)throw up.error;
    for(const d of dupes){
      const dupTags=[...new Set([...(d.tags??[]).filter((t:string)=>!t.startsWith("DUPLICATE_OF:")),"DUPLICATE_OF:"+primary.id])];
      const note=(d.notes?d.notes+" · ":"")+"Duplicado por diferença de maiúsculas/minúsculas; registro principal: "+primary.name;
      const du=await supabase.from("characters").update({monitored:false,archived:true,online:false,tags:dupTags,notes:note}).eq("id",d.id);
      if(du.error)throw du.error;archived++;
    }
  }
  return archived;
}
export async function allCharacters(){const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("archived",false).order("name");if(error)throw error;return (data??[]).map(mapCharacter) as Character[];}
export async function characters(){return (await allCharacters()).filter(c=>c.monitored&&c.world_name===TARGET_WORLD);}
export async function character(id:string){const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("id",id).single();if(error)throw error;return mapCharacter(data);}
export async function sources(){const {data,error}=await supabase.from("source_syncs").select("*").order("source");if(error)throw error;return data as SourceSync[];}
export async function events(){const [a,b,c,d]=await Promise.all([supabase.from("online_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(100),supabase.from("death_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(100),supabase.from("level_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(50),supabase.from("pvp_events").select("*,characters(name,worlds(name))").order("occurred_at",{ascending:false}).limit(100)]);for(const r of [a,b,c,d])if(r.error)throw r.error;return [...(a.data??[]).map((x:any)=>({...x,kind:x.kind})),...(b.data??[]).map((x:any)=>({...x,kind:"DEATH"})),...(c.data??[]).map((x:any)=>({...x,kind:"LEVEL_UP"})),...(d.data??[]).map((x:any)=>({...x,kind:"PVP_KILL"}))].filter((x:any)=>x.characters?.worlds?.name===TARGET_WORLD||x.raw_data?.world===TARGET_WORLD||x.kind==="MASS_LOGIN").sort((x:any,y:any)=>new Date(y.occurred_at).getTime()-new Date(x.occurred_at).getTime());}
function tibiaInfo(j:any){const root=j?.character||j?.characters||j||{};return root?.character||root?.data||root||{}}
async function ensureWorld(name:string){const {data,error}=await supabase.from("worlds").upsert({name},{onConflict:"name"}).select("id").single();if(error)throw error;return data.id as string}
async function ensureGuild(name:string|null,worldId:string){if(!name)return null;const {data:existing}=await supabase.from("guilds").select("id").eq("name",name).eq("world_id",worldId).maybeSingle();if(existing?.id)return existing.id as string;const {data,error}=await supabase.from("guilds").insert({name,world_id:worldId}).select("id").single();if(error)throw error;return data.id as string}
export async function hydrateCharacterWorld(c:{id:string;name:string}){const r=await getTibiaDataCharacter(c.name);const info=tibiaInfo(r.data);const world=String(info?.world||"").trim();if(!world)throw new Error("Não foi possível identificar o servidor de "+c.name);const worldId=await ensureWorld(world);const guildName=typeof info.guild==="string"?info.guild:String(info.guild?.name||"").trim()||null;const guildId=await ensureGuild(guildName,worldId);const patch:any={world_id:worldId,guild_id:guildId,source:"TIBIADATA",data_state:"ATUALIZADO"};if(info?.name)patch.name=String(info.name).trim();if(Number(info.level))patch.level=Number(info.level);if(info.vocation)patch.vocation=String(info.vocation);if(world!==TARGET_WORLD)patch.monitored=false;const {error}=await supabase.from("characters").update(patch).eq("id",c.id);if(error)throw error;return {world,guild:guildName,level:Number(info.level)||null,vocation:info.vocation??null}}
export async function hydratePendingWorlds(limit=1){const rows=await allCharacters();const pending=rows.filter(c=>!c.world_name).slice(0,limit);for(const c of pending){try{await hydrateCharacterWorld(c)}catch(e){console.warn("Falha ao identificar servidor",c.name,e)}}return pending.length}
function accountCharacters(j:any){const root=j?.character||j?.characters||j||{};const list=root?.other_characters??root?.otherCharacters??root?.data?.other_characters??root?.data?.otherCharacters??[];return (Array.isArray(list)?list:[]).map((o:any)=>typeof o==="string"?{name:o,world:null}:{name:String(o?.name||"").trim(),world:o?.world?String(o.world):null}).filter((o:any)=>o.name)}
async function linkPublicAccount(aId:string,bId:string,aName:string,bName:string,url:string){if(aId===bId)return;const [character_a_id,character_b_id]=[aId,bId].sort();const {data:rel,error}=await supabase.from("player_relations").upsert({character_a_id,character_b_id,status:"CONFIRMED",confidence_score:100,manual_note:"Mesma conta pública no TibiaData/Tibia.com",reviewed_at:new Date().toISOString()},{onConflict:"character_a_id,character_b_id"}).select("id").single();if(error||!rel)return;await supabase.from("relation_evidence").upsert({relation_id:rel.id,source:"TIBIADATA",evidence_type:"SAME_PUBLIC_ACCOUNT",summary:aName+" e "+bName+" aparecem na mesma conta pública",weight:100,reference_url:url,raw_data:{character:aName,other:bName}},{onConflict:"relation_id,evidence_type,source"})}
async function ensurePublicAccountCharacter(entry:{name:string;world:string|null}){let ch=await findCharacterInsensitive(entry.name);const baseTags=[...new Set([...(ch?.tags??[]),"PUBLIC_ACCOUNT_CHAR",...(entry.world&&entry.world!==TARGET_WORLD?["EXTERNAL_ACCOUNT_CHAR"]:[])])];let id=ch?.id as string|undefined;if(!id){let worldId:string|null=null;if(entry.world)worldId=await ensureWorld(entry.world);const ins=await supabase.from("characters").insert({name:entry.name,world_id:worldId,monitored:entry.world===TARGET_WORLD,archived:false,source:"TIBIADATA",data_state:"ACCOUNT_LINKED",confidence:"HIGH",tags:baseTags}).select("id,name,tags,level,updated_at,worlds(name)").single();if(ins.error)throw ins.error;ch=ins.data;id=ins.data.id}else{const patch:any={tags:baseTags,archived:false};if(entry.world){patch.world_id=await ensureWorld(entry.world);patch.monitored=entry.world===TARGET_WORLD?true:ch.monitored}const up=await supabase.from("characters").update(patch).eq("id",id).select("id,name,tags,level,updated_at,worlds(name)").single();if(!up.error)ch=up.data}return ch}
export async function syncPublicAccountLinks(c:{id:string;name:string},profileLimit=2){const r=await getTibiaDataCharacter(c.name);const url="https://api.tibiadata.com/v4/character/"+encodeURIComponent(c.name);const others=accountCharacters(r.data).filter((o:any)=>normName(o.name)!==normName(c.name));let hydrated=0,linked=0;for(const o of others){try{let other=await ensurePublicAccountCharacter(o);if(!other?.id)continue;await linkPublicAccount(c.id,other.id,c.name,other.name,url);linked++;const stale=!other.level||!other.updated_at||(Date.now()-new Date(other.updated_at).getTime()>24*60*60*1000);if(stale&&hydrated<profileLimit){const detail=await getTibiaDataCharacter(other.name);const info=tibiaInfo(detail.data);const world=String(info?.world||o.world||"").trim();if(world){const worldId=await ensureWorld(world);const guildName=typeof info.guild==="string"?info.guild:String(info.guild?.name||"").trim()||null;const guildId=await ensureGuild(guildName,worldId);const tags=[...new Set([...(other.tags??[]),"PUBLIC_ACCOUNT_CHAR",...(world!==TARGET_WORLD?["EXTERNAL_ACCOUNT_CHAR"]:["AUTO_DISCOVERED"])])];await supabase.from("characters").update({name:String(info?.name||other.name).trim(),world_id:worldId,guild_id:guildId,level:Number(info.level)||other.level||null,vocation:info.vocation?String(info.vocation):null,monitored:world===TARGET_WORLD?true:false,archived:false,source:"TIBIADATA",data_state:"ACCOUNT_LINKED",confidence:"HIGH",tags}).eq("id",other.id);hydrated++}}}catch(e){console.warn("Falha ao sincronizar char da mesma conta",c.name,o.name,e)}}return {linked,hydrated,total:others.length}}
export async function addCharacter(name:string){const clean=name.trim();if(!clean)throw new Error("Informe o nome do personagem");const existing=await findCharacterInsensitive(clean);let id=existing?.id as string|undefined;let tags=[...new Set([...(existing?.tags??[]),"PK_SEED"])];if(!id){const ins=await supabase.from("characters").insert({name:clean,monitored:true,source:"MANUAL",data_state:"PENDENTE",confidence:"LOW",tags:["PK_SEED"]}).select("id,name").single();if(ins.error)throw ins.error;id=ins.data.id}else{await supabase.from("characters").update({tags,monitored:true,archived:false}).eq("id",id)}const info=await hydrateCharacterWorld({id,name:clean});if(info.world!==TARGET_WORLD){await supabase.from("characters").update({monitored:false}).eq("id",id);throw new Error(clean+" está em "+info.world+". O PK Radar agora monitora apenas "+TARGET_WORLD+".")}await supabase.from("characters").update({monitored:true,archived:false,tags}).eq("id",id);const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("id",id).single();if(error)throw error;return mapCharacter(data);}
export async function addDiscoveredCharacter(name:string,depth:number){const clean=name.trim();if(!clean)throw new Error("Nome vazio");const existing=await findCharacterInsensitive(clean);let id=existing?.id as string|undefined;const current=existing?.tags??[];const seed=current.includes("PK_SEED");const tags=seed?current:[...new Set([...current.filter((t:string)=>t!=="AUTO_NOISE"&&!t.startsWith("DISCOVERY_DEPTH:")),"AUTO_DISCOVERED","DISCOVERY_DEPTH:"+Math.max(1,depth)])];if(!id){const ins=await supabase.from("characters").insert({name:clean,monitored:true,source:"TIBIA_STALKER",data_state:"AUTO_DESCOBERTO",confidence:"MEDIUM",tags}).select("id,name").single();if(ins.error)throw ins.error;id=ins.data.id}else{await supabase.from("characters").update({tags,monitored:true,archived:false}).eq("id",id)}const info=await hydrateCharacterWorld({id,name:clean});if(info.world!==TARGET_WORLD){await supabase.from("characters").update({monitored:false}).eq("id",id);throw new Error(clean+" não está em "+TARGET_WORLD)}await supabase.from("characters").update({monitored:true,archived:false,tags}).eq("id",id);const {data,error}=await supabase.from("characters").select("*,worlds(name),guilds(name)").eq("id",id).single();if(error)throw error;return mapCharacter(data);}
export async function syncMassOnlineState(at=new Date().toISOString()){const list=await characters();const online=list.filter(c=>c.online).sort((a,b)=>a.name.localeCompare(b.name));const names=online.map(c=>c.name);const {data:state,error}=await supabase.from("source_syncs").select("id,config").eq("source","MANUAL").maybeSingle();if(error)throw error;const config=(state?.config&&typeof state.config==="object")?state.config as Record<string,any>:{};const wasActive=Boolean(config.mass_online_active);let episode=Number(config.mass_online_episode||0);let next={...config,mass_online_active:online.length>=4,mass_online_count:online.length,mass_online_names:names,mass_online_checked_at:at};if(online.length>=4&&!wasActive){episode+=1;next={...next,mass_online_episode:episode,mass_online_started_at:at};const dedupe="mass-online:"+episode;await supabase.from("alerts").upsert({title:"MASS LOG DETECTADO",body:names.length+" personagens monitorados estão online ao mesmo tempo: "+names.join(", "),triggered_at:at,dedupe_key:dedupe,metadata:{count:names.length,threshold:4,names,rule:"CONCURRENT_ONLINE"}},{onConflict:"dedupe_key"});await supabase.from("online_events").upsert({kind:"MASS_LOGIN",occurred_at:at,source:"TIBIA_STALKER",confidence:"HIGH",dedupe_key:"mass-online-event:"+episode,metadata:{count:names.length,threshold:4,names,rule:"CONCURRENT_ONLINE"}},{onConflict:"dedupe_key"})}else if(online.length<4&&wasActive){next={...next,mass_online_ended_at:at,mass_online_episode:episode}}if(state?.id){const {error:updateError}=await supabase.from("source_syncs").update({config:next}).eq("id",state.id);if(updateError)throw updateError}else{const {error:insertError}=await supabase.from("source_syncs").upsert({source:"MANUAL",enabled:true,status:"SUCCESS",config:next},{onConflict:"source"});if(insertError)throw insertError}return {active:online.length>=4,count:online.length,names,episode}}
export async function updateOnline(name:string,isOnline:boolean,occurredOn:string,source:"TIBIA_STALKER"|"TIBIADATA"="TIBIA_STALKER"){const char=await findCharacterInsensitive(name);if(!char||char.worlds?.name!==TARGET_WORLD)return;if(char.online===isOnline)return;const occurred=new Date(occurredOn||Date.now()).toISOString();const kind=isOnline?"LOGIN":"LOGOUT";await supabase.from("characters").update({online:isOnline,last_login_at:isOnline?occurred:undefined,last_event_at:occurred,source,data_state:"ATUALIZADO",confidence:source==="TIBIA_STALKER"?"HIGH":"MEDIUM"}).eq("id",char.id);await supabase.from("online_events").upsert({character_id:char.id,kind,occurred_at:occurred,source,confidence:source==="TIBIA_STALKER"?"HIGH":"MEDIUM",dedupe_key:`${source.toLowerCase()}:${name.toLowerCase()}:${kind}:${occurred}`,metadata:{name,reconciled:source==="TIBIADATA"}},{onConflict:"dedupe_key"});await syncMassOnlineState(occurred)}
function onlineNamesFromWorld(j:any){const list=j?.world?.online_players??j?.world?.players_online??j?.worlds?.players_online??j?.players_online??[];return new Set((Array.isArray(list)?list:[]).map((x:any)=>String(x?.name??x).toLowerCase()))}
export async function reconcileWorldOnline(emitEvents=false){const r=await fetch(`https://api.tibiadata.com/v4/world/${encodeURIComponent(TARGET_WORLD)}`,{headers:{accept:"application/json"}});if(!r.ok)throw new Error("TibiaData world HTTP "+r.status);const online=onlineNamesFromWorld(await r.json());const list=await characters();const now=new Date().toISOString();let changed=0;for(const ch of list){const next=online.has(ch.name.toLowerCase());if(next===ch.online)continue;changed++;if(emitEvents)await updateOnline(ch.name,next,now,"TIBIADATA");else await supabase.from("characters").update({online:next,source:"TIBIADATA",data_state:"ATUALIZADO",confidence:"MEDIUM"}).eq("id",ch.id)}if(!emitEvents)await syncMassOnlineState(now);return {online:online.size,changed}}
