export const STALKER_API="https://api.tibiastalker.pl";export const STALKER_WS="wss://api.tibiastalker.pl/connection-hub";export const TIBIADATA_API="https://api.tibiadata.com/v4";
export async function getTibiaDataCharacter(name:string){const url=`${TIBIADATA_API}/character/${encodeURIComponent(name)}`;const r=await fetch(url,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`TibiaData HTTP ${r.status}`);return {url,data:await r.json()};}
export async function getStalkerCharacter(name:string){const url=`${STALKER_API}/api/tibia-stalker/v1/characters/${encodeURIComponent(name)}`;const r=await fetch(url,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`Tibia Stalker HTTP ${r.status}`);return {url,data:await r.json()};}
export function findOnlineFlag(value:unknown):boolean|undefined{if(!value||typeof value!=="object")return undefined;if(Array.isArray(value)){for(const x of value){const found=findOnlineFlag(x);if(found!==undefined)return found}return undefined}for(const [k,v] of Object.entries(value as Record<string,unknown>)){if(k.toLowerCase()==="isonline"&&typeof v==="boolean")return v;const found=findOnlineFlag(v);if(found!==undefined)return found}return undefined}
export type OnlineEvent={name:string;isOnline:boolean;hubEventId?:string;occurredOn?:string};
export class StalkerRealtime{private ws:WebSocket|null=null;private names:string[]=[];private onEvent:(e:OnlineEvent)=>void;private onStatus:(s:string)=>void;private retry=0;private stopped=false;private reconnectTimer:number|null=null;constructor(onEvent:(e:OnlineEvent)=>void,onStatus:(s:string)=>void){this.onEvent=onEvent;this.onStatus=onStatus}
start(names:string[]){this.names=[...new Set(names.map(x=>x.trim()).filter(Boolean))];this.stopped=false;this.connect();}
updateNames(names:string[]){this.names=[...new Set(names.map(x=>x.trim()).filter(Boolean))];if(this.ws?.readyState===WebSocket.OPEN)this.joinAll();}
stop(){this.stopped=true;if(this.reconnectTimer)window.clearTimeout(this.reconnectTimer);this.reconnectTimer=null;this.ws?.close();this.ws=null;}
private joinAll(){if(!this.ws||this.ws.readyState!==WebSocket.OPEN)return;for(const name of this.names)this.ws.send(JSON.stringify({arguments:[name],target:"JoinGroup",type:1})+"\x1e");}
private connect(){if(this.stopped)return;this.onStatus("conectando");const ws=new WebSocket(STALKER_WS);this.ws=ws;ws.onopen=()=>{this.retry=0;this.onStatus("online");ws.send(JSON.stringify({protocol:"json",version:1})+"\x1e");this.joinAll();};ws.onmessage=e=>{const raw=String(e.data);for(const frame of raw.split("\x1e").filter(Boolean)){try{const m=JSON.parse(frame);if(m.target==="Character Tracker"||m.target==="CharacterTracker"){const item=m.arguments?.[0];if(item?.name&&typeof item.isOnline==="boolean")this.onEvent(item);}else if(m.target==="JoinGroupFail"){console.warn("Tibia Stalker JoinGroupFail",m.arguments?.[0])}}catch{}}};ws.onerror=()=>this.onStatus("erro");ws.onclose=()=>{this.onStatus("desconectado");if(this.stopped)return;const delay=Math.min(30000,1000*2**Math.min(this.retry++,5));this.reconnectTimer=window.setTimeout(()=>this.connect(),delay);};}}
