const GUILD="https://guildstats.eu/character/";const RING="https://www.tibiaring.com/char.php?c=";const TIBIADATA="https://api.tibiadata.com/v4/character/";
function strip(html){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim()}
function match(text,re){const m=text.match(re);return m?.[1]?.trim()||null}
function parseDate(v){if(!v)return null;const m=v.match(/(\d{2})-(\d{2})-(\d{4})\s+(\d{2}):(\d{2})/);if(m)return new Date(Date.UTC(+m[3],+m[2]-1,+m[1],+m[4],+m[5])).toISOString();const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
async function markSource(db,source,ok,error=null){await db.from("source_syncs").update({status:ok?"SUCCESS":"ERROR",enabled:true,last_success_at:ok?new Date().toISOString():undefined,last_error:error,updated_at:new Date().toISOString()}).eq("source",source)}
async function ensureWorld(db,name){if(!name)return null;const {data}=await db.from("worlds").upsert({name},{onConflict:"name"}).select("id").single();return data?.id??null}
async function ensureGuild(db,name,worldId){if(!name)return null;let q=db.from("guilds").select("id").eq("name",name);q=worldId?q.eq("world_id",worldId):q.is("world_id",null);let {data}=await q.maybeSingle();if(data?.id)return data.id;const ins=await db.from("guilds").insert({name,world_id:worldId}).select("id").single();return ins.data?.id??null}
async function saveObservation(db,c,source,type,value,url,raw,minutes=10){await db.from("source_observations").upsert({character_id:c.id,source,observation_type:type,observed_value:value,fetched_at:new Date().toISOString(),confidence:"MEDIUM",reference_url:url,raw_data:raw,dedupe_key:source+":"+c.id+":"+type+":"+Math.floor(Date.now()/(minutes*60000))},{onConflict:"dedupe_key"})}
async function relationFromPublicAccount(db,c,other,url){const {data:b}=await db.from("characters").select("id,name").ilike("name",other).maybeSingle();if(!b||b.id===c.id)return;const aId=[c.id,b.id].sort()[0],bId=[c.id,b.id].sort()[1];const {data:rel,error}=await db.from("player_relations").upsert({character_a_id:aId,character_b_id:bId,status:"CONFIRMED",confidence_score:100,manual_note:"Mesma conta pública no TibiaData/Tibia.com",reviewed_at:new Date().toISOString()},{onConflict:"character_a_id,character_b_id"}).select("id").single();if(error||!rel)return;await db.from("relation_evidence").upsert({relation_id:rel.id,source:"TIBIADATA",evidence_type:"SAME_PUBLIC_ACCOUNT",summary:c.name+" e "+b.name+" aparecem na mesma conta pública",weight:100,reference_url:url,raw_data:{character:c.name,other:b.name}},{onConflict:"relation_id,evidence_type,source"})}
function normalizeDeath(d){const when=d.time||d.date||d.timestamp;const killers=d.killers||d.involved||[];return {at:parseDate(typeof when==="string"?when:when?.date),level:Number(d.level)||null,killers:Array.isArray(killers)?killers:[],reason:d.reason||""}}
async function syncTibiaData(db,c){const url=TIBIADATA+encodeURIComponent(c.name);try{const r=await fetch(url,{headers:{accept:"application/json"}});if(!r.ok)throw new Error("HTTP "+r.status);const j=await r.json();const root=j.character||j.characters||j;const info=root.character||root.data||root;const world=info.world||null;const guild=typeof info.guild==="string"?info.guild:info.guild?.name||null;const worldId=await ensureWorld(db,world);const guildId=await ensureGuild(db,guild,worldId);const old=(await db.from("characters").select("level").eq("id",c.id).single()).data;const level=Number(info.level)||null;const patch={source:"TIBIADATA",data_state:"ATUALIZADO",confidence:"HIGH"};if(level)patch.level=level;if(info.vocation)patch.vocation=info.vocation;if(worldId)patch.world_id=worldId;if(guildId)patch.guild_id=guildId;await db.from("characters").update(patch).eq("id",c.id);if(level&&old?.level&&level>old.level){await db.from("level_events").upsert({character_id:c.id,old_level:old.level,new_level:level,occurred_at:new Date().toISOString(),source:"TIBIADATA",confidence:"HIGH",reference_url:url,dedupe_key:"td-level:"+c.id+":"+level},{onConflict:"dedupe_key"})}
const deaths=root.deaths||[];for(const d0 of deaths){const d=normalizeDeath(d0);if(!d.at)continue;const key="td-death:"+c.id+":"+d.at+":"+(d.level??"");await db.from("death_events").upsert({character_id:c.id,occurred_at:d.at,level:d.level,killers:d.killers,source:"TIBIADATA",confidence:"HIGH",reference_url:url,raw_data:d0,dedupe_key:key},{onConflict:"dedupe_key"});const playerNames=d.killers.filter(k=>k&&typeof k==="object"&&(k.player===true||k.is_player===true||k.type==="player")).map(k=>k.name).filter(Boolean);for(const name of playerNames){await db.from("pvp_events").upsert({character_id:c.id,opponent_name:name,role:"VICTIM",occurred_at:d.at,source:"TIBIADATA",confidence:"HIGH",reference_url:url,raw_data:d0,dedupe_key:"td-pvp:"+c.id+":"+d.at+":"+String(name).toLowerCase()},{onConflict:"dedupe_key"})}}
const others=root.other_characters||root.otherCharacters||[];for(const o of others){const n=typeof o==="string"?o:o?.name;if(n)await relationFromPublicAccount(db,c,n,url)}await saveObservation(db,c,"TIBIADATA","CHARACTER_PROFILE",{level,world,guild,otherCharacters:others.map(o=>typeof o==="string"?o:o?.name).filter(Boolean)},url,j,5);await markSource(db,"TIBIADATA",true)}catch(err){console.error("TIBIADATA",c.name,err);await markSource(db,"TIBIADATA",false,String(err))}}
function playerLike(name){return /^[A-ZÀ-Ý][\p{L}' -]{1,39}$/u.test(String(name||"").trim())}
function combatRows(html){const tables=String(html).match(/<table[\s\S]*?<\/table>/gi)||[];const table=tables.find(t=>{const x=strip(t);return /(Killed|Victim|Morto|Muerto)/i.test(x)&&/(Killer|Assassino|Asesino)/i.test(x)})||html;const out=[];for(const row of String(table).match(/<tr[\s\S]*?<\/tr>/gi)||[]){const cells=[...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(m=>strip(m[1]));if(cells.length>=4)out.push(cells)}return out}
function parseRingCombat(html){const events=[];let current=null;for(const cells of combatRows(html)){const at=parseDate(cells[0]),victim=String(cells[1]||"").trim(),victimLevel=Number(cells[2])||null,killer=String(cells[3]||"").trim(),killerLevel=Number(cells[4])||null;if(at&&victim&&!/^(Killed|Victim|Morto|Muerto)$/i.test(victim)){current={at,victim,victimLevel,killers:[]};events.push(current)}if(current&&killer&&!/^(Killer|Assassino|Asesino)$/i.test(killer))current.killers.push({name:killer,level:killerLevel,player:playerLike(killer),role:current.killers.length===0?"KILLER":"ASSIST"})}return events.filter(e=>e.killers.length)}
async function saveRingCombat(db,c,html,url){for(const ev of parseRingCombat(html)){const seen=new Set(),players=[];for(const k of ev.killers){if(!k.player)continue;const key=k.name.toLowerCase();if(seen.has(key))continue;seen.add(key);players.push(k)}if(!players.length)continue;const {data:victimChar}=await db.from("characters").select("id").ilike("name",ev.victim).maybeSingle();const dedupe="ring-death:"+ev.at+":"+ev.victim.toLowerCase();await db.from("death_events").upsert({character_id:victimChar?.id??null,occurred_at:ev.at,level:ev.victimLevel,killers:players,source:"TIBIARING",confidence:"HIGH",reference_url:url,raw_data:{victim:ev.victim,victimLevel:ev.victimLevel,world:"Jadebra",sourceCharacter:c.name,allKillers:ev.killers},dedupe_key:dedupe},{onConflict:"dedupe_key"});for(const [idx,k] of players.entries()){const {data:kc}=await db.from("characters").select("id").ilike("name",k.name).maybeSingle();if(kc?.id)await db.from("pvp_events").upsert({character_id:kc.id,opponent_name:ev.victim,role:idx===0?"KILLER":"ASSIST",occurred_at:ev.at,source:"TIBIARING",confidence:"HIGH",reference_url:url,raw_data:{victim:ev.victim,participants:players},dedupe_key:"ring-pvp:"+kc.id+":"+ev.at+":"+ev.victim.toLowerCase()+":"+(idx===0?"killer":"assist")},{onConflict:"dedupe_key"})}}}
async function syncHtml(db,c,source,url){try{const r=await fetch(url,{headers:{"user-agent":"PK-Radar/2.0 public-data-monitor","accept":"text/html"}});if(!r.ok){if(source==="TIBIARING"&&r.status===403){await db.from("source_syncs").update({status:"IDLE",enabled:true,last_error:"TibiaRing bloqueou este servidor (HTTP 403). Fallback de kills pelo TibiaData deve permanecer ativo.",config:{degraded:true,fallback:"TIBIADATA_PVP_WATCH"},updated_at:new Date().toISOString()}).eq("source","TIBIARING");return}throw new Error("HTTP "+r.status)};const html=await r.text();const text=strip(html);let values={};if(source==="TIBIARING")await saveRingCombat(db,c,html,url);if(source==="GUILDSTATS"){values={level:Number((match(text,/Level\s+([0-9,]+)/i)||"").replaceAll(",",""))||null,vocation:match(text,/Vocation:\s*([A-Za-z ]+?)\s+(?:Achievements|Titles|World:)/i),world:match(text,/World:\s*([A-Za-z0-9 -]+?)\s+Residence:/i),guild:match(text,/Guild\s+(.+?)\s+since\s+/i),lastLogin:parseDate(match(text,/Last login:\s*([0-9-]+\s+[0-9:]+)/i)),online:/\bONLINE\b/i.test(text)}}else{values={level:Number(match(text,/level\s+(\d+)/i))||null,online:/\bON\b|\bONLINE\b/i.test(text),lastOnline:match(text,/Last online(?: time)?:\s*([^|]+?)(?:Power Gaming|Death penalty|$)/i)}}await saveObservation(db,c,source,"CHARACTER_PAGE",values,url,{text:text.slice(0,16000)},30);await markSource(db,source,true)}catch(err){console.error(source,c.name,err);await markSource(db,source,false,String(err))}}
export async function syncPublicSources(db,list,{deep=false,ring=deep,guild=deep}={}){for(const c of list){await syncTibiaData(db,c);if(guild)await syncHtml(db,c,"GUILDSTATS",GUILD+encodeURIComponent(c.name));if(ring)await syncHtml(db,c,"TIBIARING",RING+encodeURIComponent(c.name)+"&lang=en")}}
